<?php

use GuzzleHttp\Client;
use Laravel\Socialite\Facades\Socialite;

class LoginWithGoogleTest extends AuthLoginTest
{
	protected $driver = 'google';

	public function setUp(): void
	{
		parent::setUp(); // TODO: Change the autogenerated stub

		$this->abstractUser = Mockery::mock('Laravel\Socialite\Two\User');
		$this->abstractUser->shouldReceive('getName')->andReturn('googleUser');
		$this->abstractUser->shouldReceive('getEmail')->andReturn('florence@google.com');

		$this->provider = Mockery::mock('Laravel\Socialite\Contracts\Provider');
		$this->provider->shouldReceive('userFromToken')->andReturn($this->abstractUser);

		Socialite::shouldReceive('driver')->with($this->driver)->andReturn($this->provider);

		$this->client = Mockery::mock(Client::class);
	}

	public function testCanGenerateJWTTokenForValidUser()
	{
		$this->assertCanGenerateJWTTokenForValidUser();
	}

	public function testAssertStatusCodeIs200()
	{
		$this->assertStatusCodeIs200();
	}

	public function testSeeJWTInRedisAfterSuccessfulLogin()
	{
		$this->assertSeeJWTInRedisAfterSuccessfulLogin();
	}

	public function testCanLoginWithSoapboxSlug()
    {
        $this->assertCanLogInWithSoapboxSlug();
    }
}
