language: php

dist: bionic

php:
  - 8.0

jobs:
  fast_finish: true
  include:
    - php: 8.0
      env: DB=mysql:5.7
    - php: 8.0
      env: DB=mysql:8.0

services:
  - mysql
  - redis-server

before_install:
  - phpenv config-rm xdebug.ini
  - mysql -u root -e "CREATE USER 'homestead'@'localhost' IDENTIFIED BY 'secret';"
  - mysql -u root -e "GRANT ALL ON *.* TO 'homestead'@'localhost';"
  - composer self-update && composer install -n --prefer-dist --no-scripts -d .

script:
  - php artisan --env=example
  - ./vendor/bin/phpunit --configuration phpunit.xml
