<?php

use Laravel\Socialite\Facades\Socialite;

class LoginWithMicrosoftTest extends AuthLoginTest
{
    protected $driver = 'graph';

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->abstractUser = Mockery::mock('Laravel\Socialite\Two\User');
        $this->abstractUser->shouldReceive('getName')->andReturn('microsoftuser');
        $this->abstractUser->shouldReceive('getEmail')->andReturn('florence@outlook.com');

        $this->provider = Mockery::mock('Laravel\Socialite\Contracts\Provider');
        $this->provider->shouldReceive('userFromToken')->andReturn($this->abstractUser);

        Socialite::shouldReceive('driver')->with($this->driver)->andReturn($this->provider);
    }

    public function testCanGenerateJWTTokenForValidUser()
    {
        $this->assertCanGenerateJWTTokenForValidUser();
    }

    public function testAssertStatusCodeIs200()
    {
        $this->assertStatusCodeIs200();
    }

    public function testSeeJWTInRedisAfterSuccessfulLogin()
    {
        $this->assertSeeJWTInRedisAfterSuccessfulLogin();
    }
}
