<?php

use Carbon\Carbon;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Cache;

class LogoutTest extends TestCase
{
    protected $token;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->token = '9188040d-6c67-4c5b-b112-36a304b66dad';
    }

    public function testLogoutIsSuccessfulIfJWTTokenIsSetInRedisCache()
    {
        $ttl = Carbon::now()->addDays(1);

        Cache::add($this->token, '', $ttl); //set at login

        $this->post(
            '/logout', [],
            [
                'Authorization' => 'Bearer '.$this->token,
            ]
        )->assertResponseStatus(Response::HTTP_OK);
    }
}
